# Generated by Django 5.2.6 on 2025-11-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
