# Generated by Django 5.2.6 on 2025-11-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_mechanicrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='mechanicrating',
            options={'ordering': ['-created_at']},
        ),
    ]
