# Generated by Django 5.2.6 on 2025-11-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic_type',
            field=models.CharField(choices=[('two_wheeler', 'Two-Wheeler Mechanic'), ('automotive', 'Automotive Mechanic'), ('heavy_vehicle', 'Heavy Vehicle Mechanic')], default='automotive', max_length=50),
        ),
    ]
