# Generated by Django 5.2.6 on 2025-10-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mechanic', 'Mechanic'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
