# Generated by Django 5.2.6 on 2025-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0007_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='mechanic_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
