# Generated by Django 5.2.6 on 2025-11-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0008_mechanicprofile_mechanic_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='mechanic_types',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
